"""Added polls_time field

Revision ID: 0e72f0b4ed02
Revises: da6b3efbd4ef
Create Date: 2024-05-18 18:52:06.384848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e72f0b4ed02'
down_revision: Union[str, None] = 'da6b3efbd4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('polls_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'polls_time')
    # ### end Alembic commands ###
