"""Added message_id field

Revision ID: 541031a4d9f2
Revises: 63ffe51e36a5
Create Date: 2024-05-16 17:47:26.829014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541031a4d9f2'
down_revision: Union[str, None] = '63ffe51e36a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'message_id')
    # ### end Alembic commands ###
