"""Added initial table

Revision ID: 0294f864b518
Revises: 
Create Date: 2024-05-06 00:10:16.743439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0294f864b518'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('users',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('user_session',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('in_game', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id_'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index('user_id_session_id', 'user_session', ['user_id', 'session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_session_id', table_name='user_session')
    op.drop_table('user_session')
    op.drop_table('users')
    op.drop_table('sessions')
    # ### end Alembic commands ###
