"""Added initial tables

Revision ID: 74694cb2e040
Revises: 
Create Date: 2024-05-20 10:22:16.791500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74694cb2e040'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('polls_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('users',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.execute("CREATE SEQUENCE users_id_seq START 1")

    op.create_table('user_session',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('in_game', sa.Boolean(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id_'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index('user_id_session_id', 'user_session', ['user_id', 'session_id'], unique=True)
    op.execute("CREATE SEQUENCE user_session_id_seq START 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id_session_id', table_name='user_session')
    op.drop_table('user_session')
    op.drop_table('users')
    op.drop_table('sessions')
    op.drop_table('admins')
    # ### end Alembic commands ###
